Добавление Ef Core + небольшой рефакторинг(перевод сущностей на VO и добавление списков VO)
Top0wl/PetVolunteer pull request #5
Opened 2024-09-10 18:37 UTC by Top0wl

- Добавлен DbContext
- Добавлены Миграции
- Добавлены новые VO
- Добавлен абстрактный класс для Id
- Добавлен Docker

2024-09-11 06:30 UTC, KirillSachkov requested changes

2024-09-11 06:30 UTC, KirillSachkov commented on backend/src/PetVolunteer.Domain/ValueObjects/PetPhotos.cs
> +    public List<PetPhoto> Photos { get; }
Здесь лучше фотки сделать IReadonlyList + добавить конструктор, где ты будешь принимать IEunumerable

2024-09-11 06:30 UTC, KirillSachkov commented on backend/src/PetVolunteer.Domain/ValueObjects/PetRequisites.cs
> +    public List<Requisite> Requisites { get; }
Здесь тоже самое

2024-09-11 06:30 UTC, KirillSachkov commented on backend/src/PetVolunteer.Domain/ValueObjects/PetRequisites.cs
> +public class PetRequisites
Реквизиты будут одни и у волонтера и у животного, не нужно делить на два класса

2024-09-11 06:30 UTC, KirillSachkov commented on backend/src/PetVolunteer.Domain/ValueObjects/VolunteerSocialMedias.cs
> +    public List<SocialMedia> SocialMedias { get; }
конструктор + IReadonlyList

2024-09-11 06:30 UTC, KirillSachkov commented on backend/src/PetVolunteer.Infrastructure/ApplicationDbContext.cs
> +    public DbSet<Pet> Pets { get; set; }
Для домашних животных не нужен DbSet, мы управляем животными через волонтера

2024-09-11 06:30 UTC, KirillSachkov commented on backend/src/PetVolunteer.Infrastructure/Configurations/PetConfiguration.cs
> +        builder.ToTable("Pets");
у нас  snake_case стиль наименования, значит всё должно быть с маленькой буквы

2024-09-11 06:30 UTC, KirillSachkov commented on backend/src/PetVolunteer.Infrastructure/Configurations/VolunteerConfiguration.cs
> +        builder.ToTable("Volunteers");
и здесь

2024-09-12 21:24 UTC, Asasen1 approved these changes

2024-09-12 21:24 UTC, Asasen1 commented on backend/src/PetVolunteer.API/appsettings.json
> +    "Database": "Server=127.0.0.1;Port=5434;Database=petVolunteer;User Id=postgres;Password=postgres;"
не обязательно повторять конфигурацию. Это нужно для разделения разработки и продакшена. Лучше используй user secrets

2024-09-13 04:38 UTC, merged